import '../../utils/bee'
import {
  getIntellectSearch
} from '../../api/yqMonitor'
const state = {
  pagination: {},
  intellectSearchList: [],
  searchObj: {
    timeRange: [window.Bee.DateUtils.formt((new Date(new Date().toLocaleDateString()).getTime()), 'yyyy-MM-dd HH:mm:ss'),
      window.Bee.DateUtils.formt((new Date(new Date().toLocaleDateString()).getTime() + ((24 * 60 * 60 * 1000) - 1)), 'yyyy-MM-dd HH:mm:ss')],
    wordResult: null,
    wordTop: null,
    matchType: null,
    orderType: null,
    begTimeText: '',
    endTimeText: '',
    side: null,
    siteCls: null,
    endOffset: 20,
    searchTime: 2,
  },
  listSearchParam: null,
  pageObj: {
    pageSize: 10,
    pageNo: 1
  },
  siteClsArr: []
}

const mutations = {
  searchObjChange (state, data) {
    state.searchObj = Object.assign(state.searchObj, data)
    state.pageObj = Object.assign(state.pageObj, { pageNo: 1 })
    state.listSearchParam = Object.assign(state.searchObj, state.pageObj)
  },
  pageObjChange (state, data) {
    state.pageObj = Object.assign(state.pageObj, data)
    state.listSearchParam = Object.assign({}, state.searchObj, state.pageObj)
  },
  setIntellectSearchList (state, intellectSearchList) {
    state.intellectSearchList = intellectSearchList
  },
  setPagination (state, pagination) {
    state.pagination = pagination
  },
  setSiteClsArr (state, siteClsArr) {
    state.siteClsArr = siteClsArr
  },
  initListParam (state, data) {
    state.listSearchParam = Object.assign(state.searchObj, state.pageObj, data)
  }
}

const actions = {
  searchObjChange ({ commit }, paramObj) {
    commit('searchObjChange', paramObj)
  },
  pageObjChange ({ commit }, paramObj) {
    commit('pageObjChange', paramObj)
  },
  initListParam ({ commit }, data) {
    commit('initListParam', data)
  },
  getIntellectSearch({ commit, state }) {
    getIntellectSearch(state.listSearchParam).then(res => {
      let data = res.data.data
      data = {
        'asc': true,
        'condition': null,
        'current': 1,
        'limit': 2147483647,
        'offset': 0,
        'offsetCurrent': 0,
        'openSort': true,
        'optimizeCount': false,
        'orderByField': '',
        'pages': 1390,
        'records': [{
          'accountId': '2676459461',
          'areaCode': '',
          'author': 'yy问责云昆',
          'collected': false,
          'content': "既然昆中院定泛交所案为非吸,那请追究颁发十四个红头文件发起成立并监管泛交所相关部门责任,退回导入<span class='highlight'>云南</span>实体经济的367亿及11亿税收,追回十六家银行收取的佣金并追究违规责任,追回央视各大媒体及名人站台收取的费用.公布泛案中的430亿资金去向!为22万户百姓挽回损失!让百姓也切身体会司法的公平公正!",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:38:53',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:39:47',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': 'yy问责云昆',
          'operationData': false,
          'readed': 0,
          'rowkey': '1265c7d56f294b3c_20191213173947_897c675',
          'showTime': '2019-12-13 17:39:47',
          'showWords': [],
          'side': 1,
          'simId': '06f92f8f238f1b0fa27b4d2fe516cbbf',
          'simNum': 13,
          'siteCls': '1048576',
          'siteName': '新浪微博',
          'subName': '新浪微博-yy问责云昆',
          'title': "既然昆中院定泛交所案为非吸,那请追究颁发十四个红头文件发起成立并监管泛交所相关部门责任,退回导入<span class='highlight'>云南</span>实体经济的367亿及11亿税收,追回十六家银行收取的佣金并追究违规责任,追回央视各大媒体及名人站台收取的费用.公布泛案中的430亿资金去向!为22万户百姓挽回损失!让百姓也切身体会司法的公平公正!",
          'url': 'https://m.weibo.cn/detail/4449093386999181',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '',
          'areaCode': '',
          'author': '',
          'collected': false,
          'content': "　　医药网12月13日讯　当归是中国传统常用中药材。上海中医药大学12日披露，国际标准化组织（ISO）正式发布了《中医药-当归药材》国际标准（ISO22584：2019TraditionalChinesemedicine–Angelicasinensisroot）。 　　该标准由上海中医药大学中药标准化研究团队主导制定。当归药材的ISO国际标准是在《香港中药材标准》当归药材标准的基础上，遵循ISO国际标准编制规则，主要从当归的性状指标等方面开展标准制定，并根据国际市场的要求，合理规定了部分农药和重金属控制指标。 　　当归始载于东汉末年的《神农本草经》，药用历史悠久。其性味甘、辛、温，具有补血活血、调经止痛、润肠通便等功效，临床常用于血虚萎黄、眩晕心悸、月经不调、经闭痛经等症，为中国历代医家常用之要药，素有“十方九归”之说，为应用最广泛的中药品种之一。 　　当归在海内外市场均享有很高的知名度，常年出口到亚洲、欧洲、美洲等20多个国家和地区。据了解，当归传统栽培资源主要分布于中国甘肃、<span class='highlight'>云南</span>、四川、湖北等省区，由于药用需求量增加，现在陕西、宁夏、山西和贵州也有引种栽培，而不同地区栽培的当归在品质上存在明显差异。 　　据了解，为了适应当归产业链的快速发展，提升当归产品的国际影响力和竞争力，由上海中医药大学徐红研究员、杨莉研究员、王峥涛教授与香港科技大学詹华强教授、董婷霞博士合作组成的研究团队，于2016年1月向相关对口单位递交了《中医药—当归药材》标准提案。2017年6月，该提案通过投票，被正式立项，共有来自中国、加拿大、澳大利亚、日本和荷兰的提名专家与项目团队共同制定标准。该标准制作历时30个月，最终于2019年12月正式出版。 　　上海中医药大学方面表示，该标准的制定将为推动当归国际标准化发展起到很好的引领作用；对提升当归产品的国际影响力和竞争力，推动当归产品的国际贸易发挥重要的作用。 　　据悉，上海中医药大学中药标准化教育部重点实验室、中药新资源与品质评价国家中医药管理局重点研究室、上海中药标准化研究中心多年来一直致力于中药标准化研究，其专家团队长期参与中国药典、香港中药材标准、欧美药典、WHO以及ISO国际标准制定，在中药国际标准领域具有较强的团队实力与优势。（完） 医药网新闻；",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:38:42',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:39:39',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '',
          'operationData': false,
          'readed': 0,
          'rowkey': '2433bbd022384089_20191213000000_7c8ba90',
          'showTime': '2019-12-13 17:39:39',
          'showWords': [],
          'side': 1,
          'simId': 'e55a22dde2b13c096caafa003180a36b',
          'simNum': 35,
          'siteCls': '1',
          'siteName': '100医药网',
          'subName': '100医药网-资讯',
          'title': '《中医药',
          'url': 'https://news.100yiyao.com/detail/193555530.html',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '3840904562',
          'areaCode': '',
          'author': '昆明官渡发布',
          'collected': false,
          'content': "#<span class='highlight'>云南</span>旅游# 冬季，是昆明红嘴鸥、冬樱花霸屏的季节。明天周末，哪里打卡呢？ ​",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:38:53',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:39:37',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '昆明官渡发布',
          'operationData': false,
          'readed': 0,
          'rowkey': '805d177ef5a493c1_20191213173937_0a935e3',
          'showTime': '2019-12-13 17:39:37',
          'showWords': [],
          'side': 0,
          'simId': 'c99655b92c1603231bbb28e0a552ab2a',
          'simNum': -1,
          'siteCls': '1048576',
          'siteName': '新浪微博',
          'subName': '新浪微博-微博关键字搜索',
          'title': "#<span class='highlight'>云南</span>旅游# 冬季，是昆明红嘴鸥、冬樱花霸屏的季节。明天周末，哪里打卡呢？ ​",
          'url': 'https://weibo.com/3840904562/IkB6Ajgjv?refer_flag=1001030103_',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '6107694040',
          'areaCode': '',
          'author': '轰隆冰梆梆',
          'collected': false,
          'content': ".      我是一名普通的旅客，于2019年12月13日上午，乘坐高铁D8688次列车从昆明到祥云站，由于我的一时疏忽，不慎将身份证遗忘在03车厢16A号上。在离开祥云站时才发现自己的身份证已丢失，当时我就急忙拨打12306声讯电话，正当万分焦急的时候，高铁D8688次列车长给我打来电话，告诉我身份证丢在动车上了。由于家在临沧，路程较远，列车长提出将身份证邮寄过来，当时我怀着感激之情询问他的尊姓大名，他只告诉我是列车长，是他应该做的。此时我的心中肃然升起一种无比感激之情。在我高兴与激动之余我深深被列车长同志这种急他人所急的高尚品质感动。       最后，请接受我向铁路集团<span class='highlight'>云南</span>铁路局领导及动车D8688次列车长和全体乘务员同志致以最诚挚的感谢，是您们的辛勤工作、无悔付出，使广大旅客安全、舒适的抵达目的地，您们是全国铁路的窗口，人民心中的铁路卫士，您们永远是乘客心中最可爱的人。祝铁路集团<span class='highlight'>云南</span>铁路局领导及动车D8688次列车长和全体乘务员工作顺利、阖家幸福！",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:38:48',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:39:37',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '轰隆冰梆梆',
          'operationData': false,
          'readed': 0,
          'rowkey': '03267b655b5bf653_20191213173937_a16ffa7',
          'showTime': '2019-12-13 17:39:37',
          'showWords': [],
          'side': 1,
          'simId': '393ee327bf2c586bb53eb189f3fe49ec',
          'simNum': 0,
          'siteCls': '1048576',
          'siteName': '新浪微博',
          'subName': '新浪微博-微博关键字搜索',
          'title': ".      我是一名普通的旅客，于2019年12月13日上午，乘坐高铁D8688次列车从昆明到祥云站，由于我的一时疏忽，不慎将身份证遗忘在03车厢16A号上。在离开祥云站时才发现自己的身份证已丢失，当时我就急忙拨打12306声讯电话，正当万分焦急的时候，高铁D8688次列车长给我打来电话，告诉我身份证丢在动车上了。由于家在临沧，路程较远，列车长提出将身份证邮寄过来，当时我怀着感激之情询问他的尊姓大名，他只告诉我是列车长，是他应该做的。此时我的心中肃然升起一种无比感激之情。在我高兴与激动之余我深深被列车长同志这种急他人所急的高尚品质感动。       最后，请接受我向铁路集团<span class='highlight'>云南</span>铁路局领导及动车D8688次列车长和全体乘务员同志致以最诚挚的感谢，是您们的辛勤工作、无悔付出，使广大旅客安全、舒适的抵达目的地，您们是全国铁路的窗口，人民心中的铁路卫士，您们永远是乘客心中最可爱的人。祝铁路集团<span class='highlight'>云南</span>铁路局领导及动车D8688次列车长和全体乘务员工作顺利、阖家幸福！",
          'url': 'https://weibo.com/6107694040/IkB89e4nP?refer_flag=1001030103_',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '5134913472',
          'areaCode': '',
          'author': '学者274',
          'collected': false,
          'content': "直辖市省会自治区首府赋诗26                   七律 <span class='highlight'>云南</span>昆明        屏蔽三山四季春，滇池妩媚映龙门。碧鸡昂首鸣银柱，金马腾空踏彩云。古寺藏林一凤舞，翠湖喷浪九龙吟。长联邀月千年赏，诗句风流自有神。 2沈阳·富丽阳光二期 ​",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:38:53',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:39:37',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '学者274',
          'operationData': false,
          'readed': 0,
          'rowkey': '2a2069727af44228_20191213173937_cd7f4d8',
          'showTime': '2019-12-13 17:39:37',
          'showWords': [],
          'side': 1,
          'simId': '8418e6c815f9e44aa809e83eadae084d',
          'simNum': -1,
          'siteCls': '1048576',
          'siteName': '新浪微博',
          'subName': '新浪微博-微博关键字搜索',
          'title': "直辖市省会自治区首府赋诗26                   七律 <span class='highlight'>云南</span>昆明        屏蔽三山四季春，滇池妩媚映龙门。碧鸡昂首鸣银柱，金马腾空踏彩云。古寺藏林一凤舞，翠湖喷浪九龙吟。长联邀月千年赏，诗句风流自有神。 2沈阳·富丽阳光二期 ​",
          'url': 'https://weibo.com/5134913472/IkB6rajhr?refer_flag=1001030103_',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '',
          'areaCode': '',
          'author': '地方商务',
          'collected': false,
          'content': "（中国商务新闻网讯）12月11日，据<span class='highlight'>云南</span>大理州文化和旅游局消息，2020《中国好声音》大理州宾川县“我为家乡代言”一县一品巡演巡展系列活动暨“瓜果飘香灵山端·百家媒体看宾川”大型媒体采风活动，将于12月18日正式开始。 据悉，2020《中国好声音》大理州宾川县“我为家乡代言”一县一品巡演巡展系列活动暨“瓜果飘香灵山端·百家媒体看宾川”大型媒体采风活动将邀请国内20余家媒体赴宾川参加媒体采风活动，同时还有数十家外场媒体参与本次活动的报道。 本次媒体采风活动，主要以推广和宣传宾川丰富的旅游资源、声名远扬的佛教圣地、史迹和灿烂的民俗文化资源以及农业生态资源为中心。推动国内媒体聚焦宾川鸡足山盛景和“水果之乡”美誉，展示乡村旅游建设的成果。 此次活动将通过媒体的视觉将宾川丰富的产业资源展示给国内外友人，是贯彻落实“乡村振兴”战略，推动宾川县全域旅游和农业产业进一步发展和扩大宣传的一次大型创新活动。同时也是为了积极配合开展大理州宾川县创建国家全域旅游示范区宣传活动，实践新时代文明，发展旅游文化，向外界展示和推荐宾川的重要活动。 此次活动宣传重点将围绕宾川特色而展开，旨在宣传宾川，看见宾川，并且将鸡足山景区以及宾川的红色旅游村——新庄村作为重点而展开。 据了解，宾川县依托得天独厚的资源禀赋和优势条件，突显以高原特色农业引领农业产业发展，并且大力推进农业结构调整。其中优质水果、特色蔬菜、经济林果、烤烟、中药材、畜牧养殖六大高原特色产业发展已取得重大成效。此次主要围绕葡萄、柑橘、咖啡、核桃等创意生态农业和庄园经济农业为重点展开宣传。 鸡足山景区作为大理久负盛名的旅游景点，已成为宾川县一张靓丽的风景名片，鸡足山景区是省级文明风景区和国家4A级景区，本次活动也是春节前鸡足山景区做的一次重大推广和宣传活动，旨在向外宣传鸡足胜景，以此推动春节期间鸡足山景区的游客数量。 新庄村是1936年4月21日红六军团进入宾川的第一村。此次，将通过新庄“红军长征纪念馆”的落成为契机，进一步介绍乔甸镇海稍新庄村是如何将新庄村打造成现代农业、红色文化与乡村旅游一体化发展的产业融合示范村；",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:38:40',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:39:36',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '地方商务',
          'operationData': false,
          'readed': 0,
          'rowkey': '7b86a4e57c7a4f92_20191213000000_47f2d9e',
          'showTime': '2019-12-13 17:39:36',
          'showWords': [],
          'side': 1,
          'simId': '83e614965310ef7555f12eee791e5a28',
          'simNum': 1,
          'siteCls': '1',
          'siteName': '中国商务新闻网',
          'subName': '中国商务新闻网-首页',
          'title': '“瓜果飘香灵山端·百家媒体看宾川”大型媒体采风活动即将开启',
          'url': 'http://www.comnews.cn/article/local/201912/20191200028531.shtml',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '',
          'areaCode': '',
          'author': '地方商务',
          'collected': false,
          'content': "日前，以“聚力湾区，贡赢未来”为主题的广东省四川自贡商会成立大会暨自贡市招商推介会在广州举行。商会全体会员以及四川省人民政府驻广州办事处，自贡市、广州市相关部门，广东省四川商会，自贡市各异地商会出席活动。此外，自贡市相关部门还在会上推介招商政策和项目，以吸引在粤川籍企业家和广东企业家前往投资。 四川省人民政府驻广州办事处二级巡视员王强在致辞中表示，四川省在粤务工人员有三百多万，占全川在外务工人员总量的33%，而在粤的四川各级各类商会有32家。他希望把广东省四川自贡商会真正建设成在粤自贡籍企业家的家，发挥好平台、纽带、桥梁作用，实现资源互补、优势互补，共赢发展、抱团发展。他要求企业家要以市场为导向，以产业升级、创新发展规避风险应对目前不景气的经济大环境。 商会会长邓申伟表示，商会的成立，对加强自贡籍在粤企业与企业之间，企业与政府之间信息互通、资源共享、平台互助具有重要意义。商会成立后，将秉承“团结、交流、拓展、服务”宗旨创新发展，同时为会员搭建话语平台，提供产品传播平台，实现以商会友、以友促商、互动互利、共筑平台。并不忘初心，回报桑梓，为自贡市的招商引资、返乡创业、精准扶贫、社会公益等做好服务，为家乡经济发展尽一份力量。成为谋大事、创大业，为社会经济发展做出贡献的商会。 启动仪式上，邓申伟及参会嘉宾现场为商会领导班子授牌。自贡市工商业联合会在会上宣布，将其招商联络处设在广东四川自贡商会，并任命邓申伟为该联络处主任。 “（在四川）不少家庭的主要收入都靠外出务工赚取，各地汇往四川的钱，拉动当地消费，小到日常花销，大到购房买车，直至投资兴业得都有。”商会理事、从事玩具及水上用品生意的赖仕根如是说。据悉，作为劳务输出大省，四川省外出务工人员数量一直稳居全国省份前列。这些人中除了大部分工薪阶层外，亦有不少大大小小的企业家，他们不仅为四川解决了就业压力，还带回去资金、技术和理念。甚至产生了一个被民众及各级政府广泛认同的经济模式“归雁经济”，指的就是在外企业家或个人回乡兴业，有的地方政府还专门出台相关政策及措施，引导、吸收此类投资。 据了解，自贡市是四川省归雁经济发展比较突出的地区。数字显示，仅该市富顺县返乡创业企业2000多家，返乡创业人员10余万人。“归雁经济”2018年对富顺县GDP贡献率达56%、税收贡献率达70%。成为县域经济活力的重要来源，被称为“撑起县域经济发展的半边天”。 在广东省四川自贡商会的成员当中，会长邓申伟的红谷集团就属于典型的脚跨川粤两条船。该公司广州、四川设有两大生产基地，发展至今已成长为市场销售网络覆盖全国31个省市自治区及海外地区的，获得中国轻工业百强企业、中国轻工业皮革行业十强企业 、国家高新技术企业、中国箱包领先品牌等称号的大型企业。目前该公司在自贡等地已投资开发了教育、旅游、商贸等项目，并于2017年9月30日与四川省富顺县签订499亩中国西部皮具产业园，总投资36亿元。在将来，红谷集团规划是“一企三地”：广州花都作为总部推广基地，将<span class='highlight'>云南</span>丽江作为品牌文化发源地，四川富顺作为产品生产基地。 商会监事长、广东鼎一食品有限公司董事长雷云平介绍，他在自贡市沿滩区投资了西南（自贡）食品产业，规划面积6.5平方公里，计划总投资30亿元，是西南地区唯一通过区域环评和项目环评的专业食品产业园区。届时将建设至少容纳500家生产企业的西南最大食品生产聚集区、占地约100亩冷链物流中心等项目，还将打造一个能容纳3万人居住的食品特色小镇，打造宜居、宜业的产业新城，实现产城融合。；",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:38:52',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:39:36',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '地方商务',
          'operationData': false,
          'readed': 0,
          'rowkey': '0cea3423085ae113_20191213000000_ce90e1f',
          'showTime': '2019-12-13 17:39:36',
          'showWords': [],
          'side': 1,
          'simId': '63d9bbda130680a66c9078463c976b2b',
          'simNum': -1,
          'siteCls': '1',
          'siteName': '中国商务新闻网',
          'subName': '中国商务新闻网-首页',
          'title': '广东省四川自贡商会力推川粤合作',
          'url': 'http://www.comnews.cn/article/local/201912/20191200028528.shtml',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '',
          'areaCode': '',
          'author': '医药网',
          'collected': false,
          'content': "医药网12月13日讯 当归是中国传统常用中药材。上海中医药大学12日披露，国际标准化组织（ISO）正式发布了《中医药-当归药材》国际标准（ISO22584：2019TraditionalChinesemedicine–Angelicasinensisroot）。 \u00A0 该标准由上海中医药大学中药标准化研究团队主导制定。当归药材的ISO国际标准是在《香港中药材标准》当归药材标准的基础上，遵循ISO国际标准编制规则，主要从当归的性状指标等方面开展标准制定，并根据国际市场的要求，合理规定了部分农药和重金属控制指标。 \u00A0 当归始载于东汉末年的《神农本草经》，药用历史悠久。其性味甘、辛、温，具有补血活血、调经止痛、润肠通便等功效，临床常用于血虚萎黄、眩晕心悸、月经不调、经闭痛经等症，为中国历代医家常用之要药，素有“十方九归”之说，为应用最广泛的中药品种之一。 \u00A0 当归在海内外市场均享有很高的知名度，常年出口到亚洲、欧洲、美洲等20多个国家和地区。据了解，当归传统栽培资源主要分布于中国甘肃、<span class='highlight'>云南</span>、四川、湖北等省区，由于药用需求量增加，现在陕西、宁夏、山西和贵州也有引种栽培，而不同地区栽培的当归在品质上存在明显差异。 \u00A0 据了解，为了适应当归产业链的快速发展，提升当归产品的国际影响力和竞争力，由上海中医药大学徐红研究员、杨莉研究员、王峥涛教授与香港科技大学詹华强教授、董婷霞博士合作组成的研究团队，于2016年1月向相关对口单位递交了《中医药—当归药材》标准提案。2017年6月，该提案通过投票，被正式立项，共有来自中国、加拿大、澳大利亚、日本和荷兰的提名专家与项目团队共同制定标准。该标准制作历时30个月，最终于2019年12月正式出版。 \u00A0；",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:38:50',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:39:34',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '医药网',
          'operationData': false,
          'readed': 0,
          'rowkey': '896cf26815dbcff1_20191213000000_7c8ba90',
          'showTime': '2019-12-13 17:39:34',
          'showWords': [],
          'side': 1,
          'simId': 'e55a22dde2b13c096caafa003180a36b',
          'simNum': 35,
          'siteCls': '1',
          'siteName': '100医药网',
          'subName': '100医药网-资讯',
          'title': '《中医药',
          'url': 'http://news.100yiyao.com/detail/193555530.html',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '2392966812',
          'areaCode': '',
          'author': '气象上海Rainbow',
          'collected': false,
          'content': '气  象  报  告    上海中心气象台2019年12月13日17点钟发布的上海市天气预报、山东半岛南部到江苏沿海海面大风警报、长江口区及沿海海面天气预报：    今天夜里和明天上海市天气预报：    晴到多云，今天半夜到明天早晨局部地区有雾。南到西南风，明天早晨转偏北风，风力都是3-4级。明天最高温度15度，最低温度9度。明天相对湿度35%-90%。火险等级气象指数：4级，易燃。    今夜到明天长江口区及沿海海面天气预报：    长江口区：晴到多云，今天半夜到明天早晨局部有雾。南到西南风，明天上午转东北风，风力都是4-5级。    山东半岛南部沿海海面：晴到多云。西南风5-6级阵风7级，今天上半夜转偏北风6级阵风7-8级，明天下午转东北风5-6级。    江苏沿海海面：晴到多云。东南风5-6级阵风7级，今天半夜转偏北风6级阵风7-8级，明天下午转东北风5-6级。    上海市和浙江北部沿海海面：晴到多云。南到西南风，明天上午转东北风，风力都是5-6级。    浙江中部和浙江南部沿海海面：晴到多云。北到东北风5-6级。    今天温度实况：    徐家汇最高温度15.8度，最低温度8.2度；    宝　山最高温度17.2度，最低温度3.8度；    松　江最高温度17.1度，最低温度8.2度。    预报员：田洪军、陶岚、景盼盼',
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:38:53',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:39:12',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '气象上海Rainbow',
          'operationData': false,
          'readed': 0,
          'rowkey': '87a0c39a304ba99e_20191213173912_9253972',
          'showTime': '2019-12-13 17:39:12',
          'showWords': [],
          'side': 1,
          'simId': 'fe20016e604f8f734acc66c859713284',
          'simNum': -1,
          'siteCls': '1048576',
          'siteName': '新浪微博',
          'subName': '新浪微博-微博关键字搜索',
          'title': '气  象  报  告    上海中心气象台2019年12月13日17点钟发布的上海市天气预报、山东半岛南部到江苏沿海海面大风警报、长江口区及沿海海面天气预报：    今天夜里和明天上海市天气预报：    晴到多云，今天半夜到明天早晨局部地区有雾。南到西南风，明天早晨转偏北风，风力都是3-4级。明天最高温度15度，最低温度9度。明天相对湿度35%-90%。火险等级气象指数：4级，易燃。    今夜到明天长江口区及沿海海面天气预报：    长江口区：晴到多云，今天半夜到明天早晨局部有雾。南到西南风，明天上午转东北风，风力都是4-5级。    山东半岛南部沿海海面：晴到多云。西南风5-6级阵风7级，今天上半夜转偏北风6级阵风7-8级，明天下午转东北风5-6级。    江苏沿海海面：晴到多云。东南风5-6级阵风7级，今天半夜转偏北风6级阵风7-8级，明天下午转东北风5-6级。    上海市和浙江北部沿海海面：晴到多云。南到西南风，明天上午转东北风，风力都是5-6级。    浙江中部和浙江南部沿海海面：晴到多云。北到东北风5-6级。    今天温度实况：    徐家汇最高温度15.8度，最低温度8.2度；    宝　山最高温度17.2度，最低温度3.8度；    松　江最高温度17.1度，最低温度8.2度。    预报员：田洪军、陶岚、景盼盼',
          'url': 'https://weibo.com/2392966812/IkB8zcT1L?refer_flag=1001030103_',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '5899415667',
          'areaCode': '',
          'author': 'alanbnm6785nm杨文',
          'collected': false,
          'content': "#就泛亚有色事件问责云昆政府# 《泛亚案中，融资方和430亿资金去向是本质关键， 请问<span class='highlight'>云南</span>昆明政府查了没有？了解泛亚真相，就了解云昆政府在金融领域的所作所为，这不是市场行为的非法集资。这是云昆政府针对民众的金融欺诈！》#热点# #法制中国# #人民日报# @迟夙生律师#人民心声# #人民名义#",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:38:16',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:39:11',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': 'alanbnm6785nm杨文',
          'operationData': false,
          'readed': 0,
          'rowkey': 'faa28b6bef39e038_20191213173911_588d21f',
          'showTime': '2019-12-13 17:39:11',
          'showWords': [],
          'side': -1,
          'simId': '9e4e343300d8ea3ee4717261b8248236',
          'simNum': 17,
          'siteCls': '1048576',
          'siteName': '新浪微博',
          'subName': '新浪微博-alanbnm6785nm杨文',
          'title': "#就泛亚有色事件问责云昆政府# 《泛亚案中，融资方和430亿资金去向是本质关键， 请问<span class='highlight'>云南</span>昆明政府查了没有？了解泛亚真相，就了解云昆政府在金融领域的所作所为，这不是市场行为的非法集资。这是云昆政府针对民众的金融欺诈！》#热点# #法制中国# #人民日报# @迟夙生律师#人民心声# #人民名义#",
          'url': 'https://m.weibo.cn/detail/4449093176600762',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '1941176850',
          'areaCode': '',
          'author': '云南曲靖交警',
          'collected': false,
          'content': "#交管新闻# 曲靖市11月份“两客一危”车辆交通违法曝光！车属单位违法次数统计       为进一步强化曲靖市道路运输企业重点车辆及其驾驶人交通违法监管工作，督促本市道路运输企业从源头上加强重点车辆及其驾驶人的动态监管，并监督存在交通违法的重点车辆及其驾驶人及时处理和纠正超速、超员、疲劳驾驶、不按规定会车等各类交通违法行为。曲靖市公安局交警支队根据《中华人民共和国道路交通安全法》及其实施条例的相关规定，以及公安部《加强驾驶人管理指导意见》相关工作部署要求，现将曲靖市2019年11月份“两客一危”车辆道路交通违法情况进行曝光。@<span class='highlight'>云南</span>交通警察 @曲靖发布 @曲靖宣传 @曲靖政协 @曲靖政法 @曲靖警方发布 @曲靖同城  @曲靖气象 @曲靖交通广播 @微博曲靖  @问政曲靖    @曲靖人大  @曲靖政协  @曲靖组织  @曲靖宣传  @曲靖统战  @曲胜交警 @曲陆高速公路交巡警大队 @曲靖江召交警 @会泽高速交警 @曲靖麒麟交警 @宣威平安出行 @曲靖富源交警 @会泽交警hzjj @<span class='highlight'>云南</span>曲靖师宗交警 @罗平交通警察 @沾益交警 @曲靖马龙交警 @陆良交警大队 @曲靖经开交警",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:38:24',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:39:07',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '云南曲靖交警',
          'operationData': true,
          'readed': 0,
          'rowkey': 'aecff7747703ccaf_20191213173907_339d7ac',
          'showTime': '2019-12-13 17:39:07',
          'showWords': [],
          'side': 1,
          'simId': 'f5f8878903976981b3cd3f426d09f692',
          'simNum': 1,
          'siteCls': '1048576',
          'siteName': '新浪微博',
          'subName': '新浪微博-微博关键字搜索',
          'title': "#交管新闻# 曲靖市11月份“两客一危”车辆交通违法曝光！车属单位违法次数统计       为进一步强化曲靖市道路运输企业重点车辆及其驾驶人交通违法监管工作，督促本市道路运输企业从源头上加强重点车辆及其驾驶人的动态监管，并监督存在交通违法的重点车辆及其驾驶人及时处理和纠正超速、超员、疲劳驾驶、不按规定会车等各类交通违法行为。曲靖市公安局交警支队根据《中华人民共和国道路交通安全法》及其实施条例的相关规定，以及公安部《加强驾驶人管理指导意见》相关工作部署要求，现将曲靖市2019年11月份“两客一危”车辆道路交通违法情况进行曝光。@<span class='highlight'>云南</span>交通警察 @曲靖发布 @曲靖宣传 @曲靖政协 @曲靖政法 @曲靖警方发布 @曲靖同城  @曲靖气象 @曲靖交通广播 @微博曲靖  @问政曲靖    @曲靖人大  @曲靖政协  @曲靖组织  @曲靖宣传  @曲靖统战  @曲胜交警 @曲陆高速公路交巡警大队 @曲靖江召交警 @会泽高速交警 @曲靖麒麟交警 @宣威平安出行 @曲靖富源交警 @会泽交警hzjj @<span class='highlight'>云南</span>曲靖师宗交警 @罗平交通警察 @沾益交警 @曲靖马龙交警 @陆良交警大队 @曲靖经开交警",
          'url': 'https://weibo.com/1941176850/IkB85mAwc?refer_flag=1001030103_',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '',
          'areaCode': '',
          'author': '',
          'collected': false,
          'content': "本研究报告数据主要来自于国家统计局、海关总署、商务部、财政部、中投产业研究院、中投产业研究院市场调查中心、中国酒业协会以及国内外重点刊物等渠道，数据权威、详实、丰富，同时通过专业的分析预测模型，对行业核心发展指标进行科学地预测。您或贵单位若想对<span class='highlight'>云南</span>白酒市场有个系统深入的了解、或者想投资<span class='highlight'>云南</span>白酒行业，本报告将是您不可或缺的重要参考工具。",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:38:52',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:39:06',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '',
          'operationData': false,
          'readed': 0,
          'rowkey': '3481f7b052b4783b_20191213000000_c8d0c37',
          'showTime': '2019-12-13 17:39:06',
          'showWords': [],
          'side': 1,
          'simId': 'd14cf8d0c91adf1a820156ecc16cc9a3',
          'simNum': -1,
          'siteCls': '1',
          'siteName': '中国投资咨询网',
          'subName': '中国投资咨询网-中国投资咨询网',
          'title': "的发展。随后，报告对<span class='highlight'>云南</span>白酒市场做了主要企业经营状况分析和营销投资分析，最后分析了<span class='highlight'>云南</span>白酒市场的未来发展趋势。",
          'url': 'http://www.ocn.com.cn/reports/2008743yunnanbaijiu.shtml',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '2646461942',
          'areaCode': '',
          'author': '大理交警',
          'collected': false,
          'content': "#守规则平安行# 【瞠目！<span class='highlight'>云南</span>祥云：有酒一起喝 酒驾一起罚】近日，<span class='highlight'>云南</span>大理祥云交警查获了3名酒后驾车男子，令人意外的是，这三人竟是刚从酒桌上一同离开的朋友，真可谓是“有酒同喝，酒驾同罚”。 他们的“故事”是这样的，李某某、张某某和袁某某三人是朋友，三人都分别从事道路货运工作。12月10日晚，三人相约在320国道沿线祥云县板桥加油站附近餐馆就餐。期间，三人不同程度饮酒。饭后，李某某、张某某、袁某某各自驾驶云LKB129、云L06M86以及云L5M258号小型汽车返回货场。 19时30分许，行至黄里线8公里500米处时，遇上县公安局交警大队执法小分队以及<span class='highlight'>云南</span>驿、下庄派出所、交警中队民警开展交通违法整治。民警检查发现，李某某、张某某、袁某某三人均涉嫌酒后驾驶机动车。经现场酒精呼气式测试，三人血液酒精含量分别为71mg/ml、28mg/ml、38mg/ml，都已达到饮酒后驾驶机动车标准。 目前，祥云警方对李某某、张某某和袁某某三人涉嫌酒后驾驶机动车的交通违法案正在依法办理中。 @云岭政法@大理政法@公安部交通管理局@中国警察网@共青团中央@中国之声@<span class='highlight'>云南</span>省南涧县交警大队@人民公安报@中国交通频道@大理公安在线",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:38:09',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:39:03',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '大理交警',
          'operationData': true,
          'readed': 0,
          'rowkey': 'acdf98084942ca9a_20191213173903_b960d08',
          'showTime': '2019-12-13 17:39:03',
          'showWords': [],
          'side': 1,
          'simId': '9d24c7061dee1f4ecd2129fd113b1d37',
          'simNum': -1,
          'siteCls': '1048576',
          'siteName': '新浪微博',
          'subName': '新浪微博-大理交警',
          'title': "#守规则平安行# 【瞠目！<span class='highlight'>云南</span>祥云：有酒一起喝 酒驾一起罚】近日，<span class='highlight'>云南</span>大理祥云交警查获了3名酒后驾车男子，令人意外的是，这三人竟是刚从酒桌上一同离开的朋友，真可谓是“有酒同喝，酒驾同罚”。 他们的“故事”是这样的，李某某、张某某和袁某某三人是朋友，三人都分别从事道路货运工作。12月10日晚，三人相约在320国道沿线祥云县板桥加油站附近餐馆就餐。期间，三人不同程度饮酒。饭后，李某某、张某某、袁某某各自驾驶云LKB129、云L06M86以及云L5M258号小型汽车返回货场。 19时30分许，行至黄里线8公里500米处时，遇上县公安局交警大队执法小分队以及<span class='highlight'>云南</span>驿、下庄派出所、交警中队民警开展交通违法整治。民警检查发现，李某某、张某某、袁某某三人均涉嫌酒后驾驶机动车。经现场酒精呼气式测试，三人血液酒精含量分别为71mg/ml、28mg/ml、38mg/ml，都已达到饮酒后驾驶机动车标准。 目前，祥云警方对李某某、张某某和袁某某三人涉嫌酒后驾驶机动车的交通违法案正在依法办理中。 @云岭政法@大理政法@公安部交通管理局@中国警察网@共青团中央@中国之声@<span class='highlight'>云南</span>省南涧县交警大队@人民公安报@中国交通频道@大理公安在线",
          'url': 'https://m.weibo.cn/detail/4449093113747419',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '2416766134',
          'areaCode': '',
          'author': '红河交警',
          'collected': false,
          'content': "#交警正能量# 近日，一起交通事故肇事逃逸案受害者专程来到河口县交警大队，把印有“为民好警察，勇破逃逸案”字样的锦旗送到大队民警手中，并衷心的感谢河口交警破案神速，将肇事者绳之以法。@<span class='highlight'>云南</span>警方 @<span class='highlight'>云南</span>交通警察 @平安红河 ​",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:38:22',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:39:00',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '红河交警',
          'operationData': true,
          'readed': 0,
          'rowkey': 'fce8e4faa244c3c8_20191213173900_4b5a876',
          'showTime': '2019-12-13 17:39:00',
          'showWords': [],
          'side': 1,
          'simId': '0f983419c7093b6755bba7690bd06da0',
          'simNum': 1,
          'siteCls': '1048576',
          'siteName': '新浪微博',
          'subName': '新浪微博-微博关键字搜索',
          'title': "#交警正能量# 近日，一起交通事故肇事逃逸案受害者专程来到河口县交警大队，把印有“为民好警察，勇破逃逸案”字样的锦旗送到大队民警手中，并衷心的感谢河口交警破案神速，将肇事者绳之以法。@<span class='highlight'>云南</span>警方 @<span class='highlight'>云南</span>交通警察 @平安红河 ​",
          'url': 'https://weibo.com/2416766134/IkB5YbpXP?refer_flag=1001030103_',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '',
          'areaCode': '',
          'author': '',
          'collected': false,
          'content': "今日沪锡走势：今日沪锡低位运行，沪锡主力月2005合约开盘价139140元/吨，盘中最高139140元/吨，最低137860元/吨，结算价138450元/吨，收盘报137860元/吨，收盘跌1610元，跌幅1.15%；主力月2005合约成交10206手减少3726手，持仓量减少628手至20750手；今日沪锡全部合约成交20254手减少5056手，持仓量增加430手至52838手。北京时间15:00，伦锡最新价报17170美元，涨40美元。 今日现货锡价走势：12月13日ccmn长江有色网1#锡价报139500-141000元/吨，均价140250元/吨，跌750元，华通市场1#锡报价138550-141050元/吨，均价139800元，跌750元。今日<span class='highlight'>云南</span>锡业公司报云锡143000元/吨，<span class='highlight'>云南</span>乘风报价140500元/吨，贸易商报价云锡139500-140500元/吨附近；其他云字头139000-140000元/吨附近；小牌139000-139500元/吨附近。今日马来西亚现货锡价格与昨持平，报每吨17150美元，成交量为19吨，较上一日成交量上涨5.6%。 ccmn锡市分析：今日国内现货锡价下跌，持货商报价随行就市，市场供应量增加，临近周末，下游维持刚需，消费不旺难以提振成交，整体成交维持清淡态势。长江有色金属网www.ccmn.cn 电话：0592-5668838；",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:38:25',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:38:53',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '',
          'operationData': false,
          'readed': 0,
          'rowkey': '16c91ef983515fd0_20191213000000_eaf190e',
          'showTime': '2019-12-13 17:38:53',
          'showWords': [],
          'side': 1,
          'simId': 'c7b248a401d59ad73d89ab60cc974d69',
          'simNum': 4,
          'siteCls': '1',
          'siteName': '长江有色金属网',
          'subName': '长江有色金属网-长江锡业网',
          'title': '长江有色：13日锡价下跌 下游维持刚需',
          'url': 'http://sn.ccmn.cn/news/ZX003/201912/ed6b9cd5ae1a450988394bafcdd0fefc.html',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '5790153204',
          'areaCode': '',
          'author': '他们都叫我狗蛋儿祺',
          'collected': false,
          'content': "马嘉祺#马嘉祺1212生日快乐# 七彩<span class='highlight'>云南</span>马嘉祺生日应援【待编辑】 L他们都叫我狗蛋儿祺的微博视频 ​",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:38:00',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:38:48',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '他们都叫我狗蛋儿祺',
          'operationData': false,
          'readed': 0,
          'rowkey': 'cb947aa8eeb3eb17_20191213173848_b8d3ca9',
          'showTime': '2019-12-13 17:38:48',
          'showWords': [],
          'side': 0,
          'simId': '336d52667d7df66306b5ee9b5f65d438',
          'simNum': 0,
          'siteCls': '1048576',
          'siteName': '新浪微博',
          'subName': '新浪微博-微博关键字搜索',
          'title': "马嘉祺#马嘉祺1212生日快乐# 七彩<span class='highlight'>云南</span>马嘉祺生日应援【待编辑】 L他们都叫我狗蛋儿祺的微博视频 ​",
          'url': 'https://weibo.com/5790153204/IkB7q0IAT?refer_flag=1001030103_',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '',
          'areaCode': '',
          'author': '',
          'collected': false,
          'content': "2019年12月2日-3日，2019中国节能与低碳发展论坛暨2019中国节能协会年会在北京新世纪日航饭店召开。第十届全国人大常委会顾秀莲副委员长，第十届全国人大财经委主任、原铁道部部长、工程院院士傅志寰，住建部原纪检组长姚兵，国家发展改革委环资司宋常青副司长，工业和信息化部节能司尤勇副司长，国家市场监管总局计量司张益群副司长，国管局公共机构节能管理司宋春阳副司长，中国节能协会理事长、中国工程院院士江亿，国家发改委原气候司谢极巡视员，国家节能中心杨博副主任和相关部委领导等出席了会议。大会由中国节能协会房庆副理事长主持。国际铜业协会中国区总裁周胜先生、项目经理梁栋先生、赵恒谊先生和项目主管郑珊珊女士应邀出席了本次年会。 论坛以“节能低碳提质增效”为主题，深入学习贯彻党的十九大报告精神，落实“十三五”规划《纲要》要求，牢固树立社会主义生态文明观和绿色发展新理念，推动工业、交通运输和建筑等领域绿色、循环、节能、低碳和谐与可持续发展。 国际铜业协会作为中国节能协会常务理事单位，多年来一直支持工业及建筑等多领域的节能低碳可持续发展工作。12月2日，周胜总裁代表国际铜业协会出席了下午召开的中国节能协会第七届理事会第五次会议。 周胜总裁表示，生态文明建设是当前社会重要的任务之一，绿色发展将会给铜业发展带来新的机遇和挑战。 一方面，铜工业可能将面临更严格的环保和污染排放的要求；另一方面，铜作为一种绿色金属，对于促进生态文明建设有着不可忽视的作用。国际铜业协会将继续深入研究和学习绿色发展趋势及政府政策导向，讨论市场需求对铜工业绿色发展所带来的机会和挑战，促成铜产业链上下游加强沟通对话，共同促进绿色创新发展，以实现整个产业链的合作共赢。 作为中国节能协会热泵专委会常务副秘书长，赵恒谊先生在理事会上发表了演讲，介绍了热泵行业的发展现状，并表示将继续积极开展与各平行专委会等行业机构的交流合作，展开政策、技术研究和市场推广方面的工作，共同促进节能低碳清洁供热行业的绿色健康发展。 在12月3日上午举行的“2019中国节能协会创新奖颁奖典礼”上，<span class='highlight'>云南</span>铜业压铸科技有限公司和国际铜业协会共同承担的“中小型高效节能电动机用铸铜转子关键技术研究及产业化”项目喜获2019中国节能协会节能减排科技进步二等奖，该奖项由铁道部前部长傅志寰亲自颁奖，<span class='highlight'>云南</span>铜业压铸科技有限公司梁栋总经理代表项目组上台领奖。 铸铜转子电机具有效率高、成本低、重量轻、体积小、寿命长等诸多优点，相比铝转子电机，铸铜转子电机具有非常大的优势。采用铸铜转子，可使电机能耗在原有基础上降低15%-25%，电机效率可以提高2%-5%，在工业电机、军工、核电及电动汽车及工业再制造等领域具有极大的市场竞争力和优势。 早在2013年，铸铜转子技术就被列入国家发改委发布的《战略性新兴产业重点产品和服务指导目录》，是业界公认的电机高效化技术解决方案中*经济、简单的解决方案。尤其是对于旧电机淘汰替换方面，铸铜转子电机可以使用原电机机座号，只更换转子，实现低效电机高效再制造，对于推广高效节能电机具有很重要的意义。 作为一家非营利性国际组 织，国际铜业协会联合全球铜工业，致力于研究并推广铜的社会价值和有效使用，使其为经济及行业的绿色发展和提高人类生活品质作出贡献。自1995年以来，国际铜业协会在中国已开展了几十个市场推广项目，覆盖建筑、能源、电力、制冷供热、环境及可持续发展等多个领域，对促进铜工业及相关下游产业的绿色可持续发展起到了非常积极的作用。 清洁能源的应用和推广是政府节能减排大业的重要解决方案。国际铜业协会多年来一直为中小型风力发电行业相关技术标准的起草和修订工作提供研究报告和市场信息，协助地方政府和企业建立小风电或分布式发电项目的示范工程，同时还在太阳能光伏和工业电加热等领域为政府和企业提供技术支持。 在电力系统快速发展的过程中，输配电网/配电变压器所产生的损耗所占比重大，为促进配电网建设、城农网改造和提高电网经济运行水平，对配电网系统的节能改造势在必行。国际铜业协会充分利用自己的国际技术资源优势，协助政府机构制定强制标准，使其达到国际一流水品，为生产企业研发生态设计软件，使他们的产品设计和生产更经济和更有技术优势，为终端用户包括各级电网公司进行产品生命周期的评估来帮助他们选择*高性价比的产品，我们还通过需求侧管理的平台，为企业和用户提供培训，来促进电力变压器的节能与配网降损，同时确保配电系统安全、稳定、高效运行，使铜所具有的优异的导电性与机械特性来为节能减排做出贡献。；",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:37:51',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:38:48',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '',
          'operationData': false,
          'readed': 0,
          'rowkey': 'f798f3f179dc6922_20191213000000_5795040',
          'showTime': '2019-12-13 17:38:48',
          'showWords': [],
          'side': 1,
          'simId': 'f5d46e80540ff4da6af01740b6f07425',
          'simNum': 4,
          'siteCls': '1',
          'siteName': '长江有色金属网',
          'subName': '长江有色金属网-首页',
          'title': '国际铜业协会积极促进行业绿色可持续发展',
          'url': 'http://news.ccmn.cn/news//ZX018/201912/265d80fdb19b446a8af436d8a1b617a8.html',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '2646461942',
          'areaCode': '',
          'author': '大理交警',
          'collected': false,
          'content': "#冬季交通安全# 【<span class='highlight'>云南</span>剑川：异地交叉用警整治酒驾醉驾筑牢冬季交通安全防线 】12月11日，为进一步加大对辖区酒驾醉驾违法犯罪行为的打击整治力度，切实筑牢冬季道路交通事故防线，<span class='highlight'>云南</span>大理剑川县公安局交警大队组织开展酒驾醉驾夜查整治行动，联合鹤庆交警大队及支队装财科下沉警力在剑川县城区开展酒驾醉驾夜查整治行动,共查处各类交通违法行为55起，其中醉驾3起，酒驾1起，无证驾驶2起。 @云岭政法@大理政法@公安部交通管理局@中国警察网@共青团中央@中国之声@<span class='highlight'>云南</span>省南涧县交警大队@人民公安报@中国交通频道@大理公安在线",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:38:27',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:38:46',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '大理交警',
          'operationData': true,
          'readed': 0,
          'rowkey': '051b967aa9a90784_20191213173846_faaa8ec',
          'showTime': '2019-12-13 17:38:46',
          'showWords': [],
          'side': -2,
          'simId': 'dc6cb8d4a6e178efa70d59a4dc175c36',
          'simNum': 1,
          'siteCls': '1048576',
          'siteName': '新浪微博',
          'subName': '新浪微博-微博关键字搜索',
          'title': "#冬季交通安全# 【<span class='highlight'>云南</span>剑川：异地交叉用警整治酒驾醉驾筑牢冬季交通安全防线 】12月11日，为进一步加大对辖区酒驾醉驾违法犯罪行为的打击整治力度，切实筑牢冬季道路交通事故防线，<span class='highlight'>云南</span>大理剑川县公安局交警大队组织开展酒驾醉驾夜查整治行动，联合鹤庆交警大队及支队装财科下沉警力在剑川县城区开展酒驾醉驾夜查整治行动,共查处各类交通违法行为55起，其中醉驾3起，酒驾1起，无证驾驶2起。 @云岭政法@大理政法@公安部交通管理局@中国警察网@共青团中央@中国之声@<span class='highlight'>云南</span>省南涧县交警大队@人民公安报@中国交通频道@大理公安在线",
          'url': 'https://weibo.com/2646461942/IkB74rgJ4?refer_flag=1001030103_',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '2646461942',
          'areaCode': '',
          'author': '大理交警',
          'collected': false,
          'content': "#守规则平安行# 【瞠目！<span class='highlight'>云南</span>祥云：有酒一起喝 酒驾一起罚】近日，<span class='highlight'>云南</span>大理祥云交警查获了3名酒后驾车男子，令人意外的是，这三人竟是刚从酒桌上一同离开的朋友，真可谓是“有酒同喝，酒驾同罚”。     他们的“故事”是这样的，李某某、张某某和袁某某三人是朋友，三人都分别从事道路货运工作。12月10日晚，三人相约在320国道沿线祥云县板桥加油站附近餐馆就餐。期间，三人不同程度饮酒。饭后，李某某、张某某、袁某某各自驾驶云LKB129、云L06M86以及云L5M258号小型汽车返回货场。     19时30分许，行至黄里线8公里500米处时，遇上县公安局交警大队执法小分队以及<span class='highlight'>云南</span>驿、下庄派出所、交警中队民警开展交通违法整治。民警检查发现，李某某、张某某、袁某某三人均涉嫌酒后驾驶机动车。经现场酒精呼气式测试，三人血液酒精含量分别为71mg/ml、28mg/ml、38mg/ml，都已达到饮酒后驾驶机动车标准。     目前，祥云警方对李某某、张某某和袁某某三人涉嫌酒后驾驶机动车的交通违法案正在依法办理中。 @云岭政法@大理政法@公安部交通管理局@中国警察网@共青团中央@中国之声@<span class='highlight'>云南</span>省南涧县交警大队@人民公安报@中国交通频道@大理公安在线",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:38:02',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:38:46',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '大理交警',
          'operationData': true,
          'readed': 0,
          'rowkey': '0c3c6b7d725fb7b4_20191213173846_288ce40',
          'showTime': '2019-12-13 17:38:46',
          'showWords': [],
          'side': 1,
          'simId': '8f036fd3fae61747b36fea7c74c73cfc',
          'simNum': -1,
          'siteCls': '1048576',
          'siteName': '新浪微博',
          'subName': '新浪微博-微博关键字搜索',
          'title': "#守规则平安行# 【瞠目！<span class='highlight'>云南</span>祥云：有酒一起喝 酒驾一起罚】近日，<span class='highlight'>云南</span>大理祥云交警查获了3名酒后驾车男子，令人意外的是，这三人竟是刚从酒桌上一同离开的朋友，真可谓是“有酒同喝，酒驾同罚”。     他们的“故事”是这样的，李某某、张某某和袁某某三人是朋友，三人都分别从事道路货运工作。12月10日晚，三人相约在320国道沿线祥云县板桥加油站附近餐馆就餐。期间，三人不同程度饮酒。饭后，李某某、张某某、袁某某各自驾驶云LKB129、云L06M86以及云L5M258号小型汽车返回货场。     19时30分许，行至黄里线8公里500米处时，遇上县公安局交警大队执法小分队以及<span class='highlight'>云南</span>驿、下庄派出所、交警中队民警开展交通违法整治。民警检查发现，李某某、张某某、袁某某三人均涉嫌酒后驾驶机动车。经现场酒精呼气式测试，三人血液酒精含量分别为71mg/ml、28mg/ml、38mg/ml，都已达到饮酒后驾驶机动车标准。     目前，祥云警方对李某某、张某某和袁某某三人涉嫌酒后驾驶机动车的交通违法案正在依法办理中。 @云岭政法@大理政法@公安部交通管理局@中国警察网@共青团中央@中国之声@<span class='highlight'>云南</span>省南涧县交警大队@人民公安报@中国交通频道@大理公安在线",
          'url': 'https://weibo.com/2646461942/IkB8rfISf?refer_flag=1001030103_',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '3218234860',
          'areaCode': '',
          'author': '曲靖警方发布',
          'collected': false,
          'content': "#优秀社区民警#【周鹏：群众的贴心人】入警20多个春夏秋冬，时光在他脸上刻下岁月的痕迹，也在他心上镌刻下一心为民的忠诚使命，一直兢兢业业扎根在城市社区，把大街小巷的平安祥和守在身边，把辖区居民的大事小事放在眼里，把困难群众的冷暖挂在心上，他就是曲靖市公安局麒麟分局益宁派出所金牛警务室社区民警周鹏。@曲靖政法 @<span class='highlight'>云南</span>警方 L曲靖警方发布的微博视频",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:38:55',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:38:44',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '曲靖警方发布',
          'operationData': false,
          'readed': 0,
          'rowkey': '5918907b72284fe8_20191213173844_582d528',
          'showTime': '2019-12-13 17:38:44',
          'showWords': [],
          'side': 1,
          'simId': 'dc4bcb3d74a4ff192f077490e8730097',
          'simNum': -1,
          'siteCls': '1048576',
          'siteName': '新浪微博',
          'subName': '新浪微博-微博关键字搜索',
          'title': "#优秀社区民警#【周鹏：群众的贴心人】入警20多个春夏秋冬，时光在他脸上刻下岁月的痕迹，也在他心上镌刻下一心为民的忠诚使命，一直兢兢业业扎根在城市社区，把大街小巷的平安祥和守在身边，把辖区居民的大事小事放在眼里，把困难群众的冷暖挂在心上，他就是曲靖市公安局麒麟分局益宁派出所金牛警务室社区民警周鹏。@曲靖政法 @<span class='highlight'>云南</span>警方 L曲靖警方发布的微博视频",
          'url': 'https://weibo.com/3218234860/IkB75AAzc?refer_flag=1001030103_',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '1941176850',
          'areaCode': '',
          'author': '云南曲靖交警',
          'collected': false,
          'content': "#交管新闻# 曲靖市11月份“两客一危”车辆交通违法曝光！危险品运输类       为进一步强化曲靖市道路运输企业重点车辆及其驾驶人交通违法监管工作，督促本市道路运输企业从源头上加强重点车辆及其驾驶人的动态监管，并监督存在交通违法的重点车辆及其驾驶人及时处理和纠正超速、超员、疲劳驾驶、不按规定会车等各类交通违法行为。曲靖市公安局交警支队根据《中华人民共和国道路交通安全法》及其实施条例的相关规定，以及公安部《加强驾驶人管理指导意见》相关工作部署要求，现将曲靖市2019年11月份“两客一危”车辆道路交通违法情况进行曝光。@<span class='highlight'>云南</span>交通警察 @曲靖发布 @曲靖宣传 @曲靖政协 @曲靖政法 @曲靖警方发布 @曲靖同城  @曲靖气象 @曲靖交通广播 @微博曲靖  @问政曲靖    @曲靖人大  @曲靖政协  @曲靖组织  @曲靖宣传  @曲靖统战  @曲胜交警 @曲陆高速公路交巡警大队 @曲靖江召交警 @会泽高速交警 @曲靖麒麟交警 @宣威平安出行 @曲靖富源交警 @会泽交警hzjj @<span class='highlight'>云南</span>曲靖师宗交警 @罗平交通警察 @沾益交警 @曲靖马龙交警 @陆良交警大队 @曲靖经开交警",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:38:00',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:38:43',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '云南曲靖交警',
          'operationData': true,
          'readed': 0,
          'rowkey': 'ac700ab53b82a7f5_20191213173843_3b309bc',
          'showTime': '2019-12-13 17:38:43',
          'showWords': [],
          'side': 1,
          'simId': 'f5f8878903976981b3cd3f426d09f692',
          'simNum': 1,
          'siteCls': '1048576',
          'siteName': '新浪微博',
          'subName': '新浪微博-微博关键字搜索',
          'title': "#交管新闻# 曲靖市11月份“两客一危”车辆交通违法曝光！危险品运输类       为进一步强化曲靖市道路运输企业重点车辆及其驾驶人交通违法监管工作，督促本市道路运输企业从源头上加强重点车辆及其驾驶人的动态监管，并监督存在交通违法的重点车辆及其驾驶人及时处理和纠正超速、超员、疲劳驾驶、不按规定会车等各类交通违法行为。曲靖市公安局交警支队根据《中华人民共和国道路交通安全法》及其实施条例的相关规定，以及公安部《加强驾驶人管理指导意见》相关工作部署要求，现将曲靖市2019年11月份“两客一危”车辆道路交通违法情况进行曝光。@<span class='highlight'>云南</span>交通警察 @曲靖发布 @曲靖宣传 @曲靖政协 @曲靖政法 @曲靖警方发布 @曲靖同城  @曲靖气象 @曲靖交通广播 @微博曲靖  @问政曲靖    @曲靖人大  @曲靖政协  @曲靖组织  @曲靖宣传  @曲靖统战  @曲胜交警 @曲陆高速公路交巡警大队 @曲靖江召交警 @会泽高速交警 @曲靖麒麟交警 @宣威平安出行 @曲靖富源交警 @会泽交警hzjj @<span class='highlight'>云南</span>曲靖师宗交警 @罗平交通警察 @沾益交警 @曲靖马龙交警 @陆良交警大队 @曲靖经开交警",
          'url': 'https://weibo.com/1941176850/IkB7X8xr1?refer_flag=1001030103_',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '2022364304',
          'areaCode': '',
          'author': '浔阳晚报',
          'collected': false,
          'content': "#九江身边事#【九江小伙再创佳绩 “达标”东京奥运会】12月8日，在广州马拉松赛上，23岁的江西小将彭建华以2小时09分57秒的成绩第6个冲过终点线，此成绩达到了2020年东京奥运会的参赛标准，也成为我国第三个达标东京奥运会的中国田径选手！彭建华来自江西九江，是赣南师范大学体育学院的一名学生。他说，参加奥运会是每一个运动员的梦想。目前，彭建华正在<span class='highlight'>云南</span>积极备战。L都市现场的微博视频",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:37:50',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:38:34',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '浔阳晚报',
          'operationData': false,
          'readed': 0,
          'rowkey': '8e6ebb8534ab5ba7_20191213173834_fdfd5ea',
          'showTime': '2019-12-13 17:38:34',
          'showWords': [],
          'side': 2,
          'simId': '26655ce0a657ae0486a3d48fefe968fc',
          'simNum': 1,
          'siteCls': '1048576',
          'siteName': '新浪微博',
          'subName': '新浪微博-微博关键字搜索',
          'title': "#九江身边事#【九江小伙再创佳绩 “达标”东京奥运会】12月8日，在广州马拉松赛上，23岁的江西小将彭建华以2小时09分57秒的成绩第6个冲过终点线，此成绩达到了2020年东京奥运会的参赛标准，也成为我国第三个达标东京奥运会的中国田径选手！彭建华来自江西九江，是赣南师范大学体育学院的一名学生。他说，参加奥运会是每一个运动员的梦想。目前，彭建华正在<span class='highlight'>云南</span>积极备战。L都市现场的微博视频",
          'url': 'https://weibo.com/2022364304/IkB7ussCP?refer_flag=1001030103_',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '',
          'areaCode': '',
          'author': '',
          'collected': false,
          'content': "　　原标题：赵克志对公安机关扫黑除恶专项斗争监督执纪问责工作提出要求 坚持从严管党治警 强化监督执纪问责 为夺取扫黑除恶专项斗争决定性胜利作出更大贡献 　　国务委员、公安部党委书记、部长赵克志近日对全国公安机关扫黑除恶专项斗争监督执纪问责工作提出要求。他强调，党中央部署开展扫黑除恶专项斗争以来，各级公安机关和派驻公安纪检监察机构忠实履行职责、充分发挥作用，坚持刀刃向内、敢于较真碰硬，同步推进扫黑打伞，严肃查处了一批公安民警涉黑恶腐败和充当“保护伞”问题，赢得了广大人民群众的信任和支持。全国公安机关要坚持以习近平新时代中国特色社会主义思想为指导，增强“四个意识”、坚定“四个自信”、做到“两个维护”，聚焦全面从严管党治警，围绕深化扫黑打伞破网，不断强化监督执纪问责，始终保持高压震慑态势，坚决清除害群之马，着力纯洁公安队伍，为锻造“四个铁一般”公安铁军、夺取扫黑除恶专项斗争决定性胜利作出新的更大贡献。 　　全国公安机关扫黑除恶专项斗争监督执纪问责工作汇报会12日在浙江杭州召开，中央纪委国家监委驻公安部纪检监察组组长、公安部党委委员邓卫平出席并讲话。他要求，要深入学习贯彻习近平总书记关于扫黑除恶的重要指示精神，全面落实党中央决策部署，按照中央纪委国家监委、中央政法委和公安部党委工作要求，以更高的政治站位、更强的工作举措，进一步加大专项斗争监督执纪问责力度，推动“打伞破网”实现新突破。 　　邓卫平要求，要坚持有案必查、“两个一律”和“一案三查”，对队伍中出现的问题不护短、不袒护，坚决清除害群之马，纯洁公安队伍。要增强合力攻坚，在各级公安机关党委的领导下，充分发挥公安纪检监察等监督部门的职责能力，加强自办、主动参办、积极联办，切实形成更大合力。要切实压实责任，用好问责利器，层层压实责任，对敷衍应付、弄虚作假，日常履职不力、疏于监管，查处打击消极滞后、偏软偏轻等问题要严肃查处追责。要加强标本兼治，把源头治理摆在突出位置，督促整改问题，完善规章制度，开展警示教育，不断推动长效常治。要精准执纪，准确把握法律政策界限，严格依纪依法办案，防止形式主义、官僚主义，确保专项斗争沿着法治轨道深入推进，并为坚决扫黑除恶的民警撑腰鼓劲，努力营造良好政治生态。要紧密结合“不忘初心、牢记使命”主题教育，深入整治不担当不作为和执法办案领域突出问题，深入整治侵害群众利益的问题，推动解决深层次领域性问题，切实增强人民群众的获得感和安全感。 　　浙江省副省长、公安厅厅长王双全出席会议并致辞。中央纪委国家监委、中央政法委有关部门负责同志到会指导。会议通报了今年以来全国公安机关扫黑除恶专项斗争和专项斗争监督执纪问责情况，浙江、北京、天津、河南、广东、广西、<span class='highlight'>云南</span>、陕西等地驻公安厅局纪检监察组作了发言。公安部有关业务局负责同志和驻各省（区、市）公安厅局纪检监察部门负责同志参加会议。 （本网发布的信息、图片等未经我单位书面授权同意，均不得转载转发）；",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:37:29',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:38:26',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '',
          'operationData': false,
          'readed': 0,
          'rowkey': '3c29a1976d8df908_20191213000000_4952809',
          'showTime': '2019-12-13 17:38:26',
          'showWords': [],
          'side': 1,
          'simId': '1f6cdc314787286f359a0cfd67a7c01d',
          'simNum': 22,
          'siteCls': '1',
          'siteName': '贾汪区政务网',
          'subName': '贾汪区政务网-产业资源',
          'title': '赵克志：坚持从严管党治警 强化监督执纪问责',
          'url': 'http://www.xzjw.gov.cn/Item/92875.aspx',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '6107694040',
          'areaCode': '',
          'author': '轰隆冰梆梆',
          'collected': false,
          'content': ". 我是一名普通的旅客，于2019年12月13日上午，乘坐高铁D8688次列车从昆明到祥云站，由于我的一时疏忽，不慎将身份证遗忘在03车厢16A号上。在离开祥云站时才发现自己的身份证已丢失，当时我就急忙拨打12306声讯电话，正当万分焦急的时候，高铁D8688次列车长给我打来电话，告诉我身份证丢在动车上了。由于家在临沧，路程较远，列车长提出将身份证邮寄过来，当时我怀着感激之情询问他的尊姓大名，他只告诉我是列车长，是他应该做的。此时我的心中肃然升起一种无比感激之情。在我高兴与激动之余我深深被列车长同志这种急他人所急的高尚品质感动。 最后，请接受我向铁路集团<span class='highlight'>云南</span>铁路局领导及动车D8688次列车长和全体乘务员同志致以最诚挚的感谢，是您们的辛勤工作、无悔付出，使广大旅客安全、舒适的抵达目的地，您们是全国铁路的窗口，人民心中的铁路卫士，您们永远是乘客心中最可爱的人。祝铁路集团<span class='highlight'>云南</span>铁路局领导及动车D8688次列车长和全体乘务员工作顺利、阖家幸福！",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:37:19',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:38:10',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '轰隆冰梆梆',
          'operationData': false,
          'readed': 0,
          'rowkey': 'efcc44e28f8d7a68_20191213173810_eed7c9f',
          'showTime': '2019-12-13 17:38:10',
          'showWords': [],
          'side': 1,
          'simId': '2ea13af82c1853bf7dedb31229c85fd8',
          'simNum': 2,
          'siteCls': '1048576',
          'siteName': '新浪微博',
          'subName': '新浪微博-轰隆冰梆梆',
          'title': ". 我是一名普通的旅客，于2019年12月13日上午，乘坐高铁D8688次列车从昆明到祥云站，由于我的一时疏忽，不慎将身份证遗忘在03车厢16A号上。在离开祥云站时才发现自己的身份证已丢失，当时我就急忙拨打12306声讯电话，正当万分焦急的时候，高铁D8688次列车长给我打来电话，告诉我身份证丢在动车上了。由于家在临沧，路程较远，列车长提出将身份证邮寄过来，当时我怀着感激之情询问他的尊姓大名，他只告诉我是列车长，是他应该做的。此时我的心中肃然升起一种无比感激之情。在我高兴与激动之余我深深被列车长同志这种急他人所急的高尚品质感动。 最后，请接受我向铁路集团<span class='highlight'>云南</span>铁路局领导及动车D8688次列车长和全体乘务员同志致以最诚挚的感谢，是您们的辛勤工作、无悔付出，使广大旅客安全、舒适的抵达目的地，您们是全国铁路的窗口，人民心中的铁路卫士，您们永远是乘客心中最可爱的人。祝铁路集团<span class='highlight'>云南</span>铁路局领导及动车D8688次列车长和全体乘务员工作顺利、阖家幸福！",
          'url': 'https://m.weibo.cn/detail/4449092933353445',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '',
          'areaCode': '',
          'author': '',
          'collected': false,
          'content': "债券名称2018年<span class='highlight'>云南</span>省政府一般债券(六期)债券简称18<span class='highlight'>云南</span>09债券代码147741发行额(亿元)112.90发行价(元)100.00发行方式单一价格荷兰式招标期限(年)5.00发行票面利率(%)3.90上市场所上海证券交易所计息日2018-07-09到期日2023-07-09发行起始日2018-07-06发行截止日2018-07-06发行单位<span class='highlight'>云南</span>省人民政府还本付息方式按年付息到期收益率(%)剩余期限(年)发行对象全国银行间债券市场、证券交易所债券市场。采取场内挂牌和场外签订分销合同的方式分销。承销机构间不得分销。",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:38:53',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:37:31',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '',
          'operationData': false,
          'readed': 0,
          'rowkey': 'ed34bdc9b420ed1e_20191213000000_8da58aa',
          'showTime': '2019-12-13 17:37:31',
          'showWords': [],
          'side': 2,
          'simId': 'e4e88d41ef25030798047d7cda712aaa',
          'simNum': -1,
          'siteCls': '1',
          'siteName': '金融界网',
          'subName': '金融界网-金融界网',
          'title': "18<span class='highlight'>云南</span>09",
          'url': 'http://bond.jrj.com.cn/bonddetail/2/147741.shtml',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '',
          'areaCode': '',
          'author': '',
          'collected': false,
          'content': "近期，中央纪委国家监委发布公告，通报银保监会系统收受“金融土特产”问题，其中特别提到了部分党员干部在网贷清理、打击非法集资案件查办中利用职务之便，搞“特权止损”的新型腐败现象，并列出17类名贵特产特殊资源清单，作为持续整治系统党员干部谋取私利不正之风和腐败的切实举措。 从有形的“送卡塞钱”，到无形的资源腐败，当前，一些贪腐违法现象已经出现了隐蔽化、伪装化特征，反腐进入“深水区”，要严防“金融土特产式”的资源腐败。 曾几何时，一些具有地方特色的“土特产”是贪腐现象的“主流”。土特产尤其是名贵特产，是一个地区的特殊名片和经济资源。贵州茅台，<span class='highlight'>云南</span>普洱茶，景德镇陶瓷……一些所谓的土特产具有高价值、可变现等特点，部分别有用心之人动起了歪脑筋。少数不法分子打着土特产幌子行贿赂之实，土特产成了利益输送的载体。 如今，“金融土特产”贪腐现象时有出现。有形的“金融土特产”，如高端信用卡、纪念币（钞）、金融机构宣传品等“糖衣炮弹”频频“击中对象”；非实物化的“金融土特产”，也易使领导干部放松警惕，甚至滋生侥幸心理。 中央纪委国家监委的公告显示，部分银保监系统干部利用监管资源、金融央企职工利用融资贷款审批权涉嫌贪腐，一些公职人员甚至在网贷清理、打击非法集资案件查办中利用职务之便搞“特权挽损”。 反腐败斗争的实践证明，无论腐败的花样如何翻新、手段多么隐蔽，都无法改变违纪违法的本质，无法逃避被查处的命运。 日前，中央纪委国家监委驻银保监会纪检监察组，已研究出台了银保监会系统名贵特产特殊资源清单和会管单位名贵特产特殊资源清单。两份清单共开列名贵特产特殊资源17类，着重体现行业特殊性。既包括有形的特产，如高端信用卡、纪念币（钞）；又包括无形的资源，如金融监管或经营服务相关的审批权决定权、可获利内部信息和机会等。 莫伸手，伸手必被捉。随着制度更加固化，惩防机制不断完善，打击水平持续提高，无论是实物的土特产、还是非实物的监管资源，广大党员干部必须筑牢廉政防火墙、拧紧思想总开关，让政治生态更加风清气正，让政商关系更加“亲”“清”。；",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:36:27',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:37:25',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '',
          'operationData': false,
          'readed': 0,
          'rowkey': 'b2b74851157eefd6_20191213000000_4e10e4c',
          'showTime': '2019-12-13 17:37:25',
          'showWords': [],
          'side': 2,
          'simId': '76d4e3b264c949c4515636333e747a1e',
          'simNum': 10,
          'siteCls': '1',
          'siteName': '忻州在线',
          'subName': '忻州在线-法制',
          'title': '整治“金融土特产”，反腐不留死角',
          'url': 'http://www.xzrbw.com/info/1194/221768.htm',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '',
          'areaCode': '',
          'author': '',
          'collected': false,
          'content': '阅读设置 楼主正文显示宽度 全幅 2/3幅 1/2幅 跟帖显示为 表状 树状 跟帖内容 全部 楼主直播 分享 赞 快速回复；',
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:36:22',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:37:19',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '',
          'operationData': false,
          'readed': 0,
          'rowkey': 'f927066c80a14767_20191213000000_3ad840a',
          'showTime': '2019-12-13 17:37:19',
          'showWords': [],
          'side': 2,
          'simId': 'bbd34f6e3ad840ada4ec32d748cc3e73',
          'simNum': -1,
          'siteCls': '16',
          'siteName': '强国论坛',
          'subName': '强国论坛-论坛',
          'title': "党味山歌传唱入脑入心<span class='highlight'>云南</span>盈江弄璋探索党建工作新路子",
          'url': 'http://bbs1.people.com.cn/post/129/1/2/174248756.html',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '',
          'areaCode': '',
          'author': '',
          'collected': false,
          'content': "北京时间12月13日，“一带一路·七彩<span class='highlight'>云南</span>”国际足球邀请赛第二轮的比赛在昆明如期进行。最终，中国男足U20梯队2：1击败塞尔维亚超级联赛霸主贝尔格莱德红星的二队，取得赛事首胜。本场比赛取胜，不仅国足U20梯队的备战开了个好头，同时也洗刷了近期国足各级别球队接连惨败的耻辱！贝尔格莱德红星在塞尔维亚超级联赛可谓是霸主级别的存在，联赛冠军、欧冠名额基本都被其垄断。本次参加邀请赛，贝尔格莱德红星的二队也是全主力出征迎战。因此，U20梯队的小将们能收获一场胜利属实不易！ 本场比赛，发挥最亮眼的球员莫过于申花小将周俊辰。上半场比赛，周俊辰先是连过数人巧射死角破门，帮助中国队1：0领先，打破比赛僵局。随后，周俊辰又妙传助攻队友幺旭辰打进一球，把领先优势扩大到了2：0！下半场比赛，对方凭借速度优势和身体优势打出快速反击，扳回一球，比分来到2：1，但是面对状态火热的中国队，贝尔格莱德红星最终没能扳平比分，比赛以2：1结束，中国队取得了本届赛事首胜，同时也终结了国足各级别梯队的3连败。此前，国足选拔队在东亚杯1：2输给日本，国足奥运队0：1输给叙利亚国奥队，国足U20梯队也0：3输给了莫斯科斯巴达的二队。如今国足、国奥的比赛还没来到第二轮，国青队的小伙子们率先用一场胜利吹响了国足各级别梯队反击的号角！ 值得一提的是，本场比赛中闪耀全场的小将周俊辰可谓是王者归来。去年远赴泰国参加曼谷杯比赛的周俊辰，因为纪律原因被足协枪打出头鸟，重罚禁赛1年。遭到重罚后，周俊辰开始了漫长的救赎之路。在足球方面，周俊辰每天保持着高强度的训练，不断加练。此外，周俊辰还边训练边继续学业，此前他已经拿到了同济大学的录取通知书。由于良好的表现和认错态度，周俊辰被足协提前解禁复出，回到了申花俱乐部。本赛季，周俊辰代表申花在联赛中出场6次。虽然出场时间比较短，但还是能看出他不凡的实力和极高的天赋。假以时日，他定能成为申花、国足的栋梁球员。 知耻而后勇，周俊辰遭禁赛1年后王者归来，国青队也在开门黑之后取得首胜。希望国足成年队、奥运队都能学习小弟们的这种精神，打好接下来各自的比赛。；",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:38:10',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:37:08',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '',
          'operationData': false,
          'readed': 0,
          'rowkey': '65d40033b71507a6_20191213000000_c2c2950',
          'showTime': '2019-12-13 17:37:08',
          'showWords': [],
          'side': 1,
          'simId': '93cb3416fb54456a5aac26dccbdc2011',
          'simNum': -1,
          'siteCls': '1',
          'siteName': '趣头条',
          'subName': '趣头条-体育',
          'title': '知耻而后勇！国足青年队2：1取首胜，终结近期各级别国足三连败',
          'url': 'https://html2.qktoutiao.com/detail/2019/12/13/1467931715.html?ispc=1',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '5899415667',
          'areaCode': '',
          'author': 'alanbnm6785nm杨文',
          'collected': false,
          'content': "#扫黑除恶在行动# 何时督办云昆政府发起成立监管的泛亚有色金属交易所大案要案，泛交所是<span class='highlight'>云南</span>政府发起成立，四年间与十六大银行战略合作，一味向人民索取，宣称保本保息随进随出，直到骗光最后一分积蓄，众多企业获利赚的盆满钵满，为实体经济导入367亿，税收11亿，而后冠于“非法集资”坑害百姓！",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:38:49',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:37:06',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': 'alanbnm6785nm杨文',
          'operationData': false,
          'readed': 0,
          'rowkey': 'e0d3ae18ea0f1599_20191213173706_37d9911',
          'showTime': '2019-12-13 17:37:06',
          'showWords': [],
          'side': -1,
          'simId': '0493b038e00eec53c5e47b5619e57a0e',
          'simNum': 14,
          'siteCls': '1048576',
          'siteName': '新浪微博',
          'subName': '新浪微博-alanbnm6785nm杨文',
          'title': "#扫黑除恶在行动# 何时督办云昆政府发起成立监管的泛亚有色金属交易所大案要案，泛交所是<span class='highlight'>云南</span>政府发起成立，四年间与十六大银行战略合作，一味向人民索取，宣称保本保息随进随出，直到骗光最后一分积蓄，众多企业获利赚的盆满钵满，为实体经济导入367亿，税收11亿，而后冠于“非法集资”坑害百姓！",
          'url': 'https://m.weibo.cn/detail/4449092543744500',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }, {
          'accountId': '',
          'areaCode': '',
          'author': '',
          'collected': false,
          'content': "中央纪委国家监委网站10月25日发布数据显示，2019年9月全国查处违反中央八项规定精神问题5016起，处理6983人，其中给予党纪政务处分5122人，涉地厅级干部46名。从查处问题类型看，违规收送礼品礼金、违规发放津补贴或福利、违规公款吃喝位列前三。 10月23日，最高法向全国人大常委会报告2014年以来加强刑事审判工作情况。2014年以来，各级法院审结一审贪污贿赂、渎职等案件19.4万件20.7万人，其中被告人原为中管干部140人，依法审理周永康、郭伯雄、孙政才、令计划、苏荣等重大职务犯罪案件，加大对行贿犯罪惩治力度，判处罪犯1.4万人。 案件方面，多只“大老虎”案传来新消息：全国人大原内司委副主任委员、<span class='highlight'>云南</span>省委原书记秦光荣被检察机关决定逮捕，内蒙古自治区人民政府原副主席白向群案一审宣判。此外，中国华电集团原党组副书记、总经理云公民接受审查调查，中国南方电网原党组书记、董事长李庆奎受到留党察看二年处分。 10月24日，辽宁省大连市中级人民法院公开宣判内蒙古自治区人民政府原副主席白向群受贿，贪污，内幕交易、泄露内幕信息案，认定被告人白向群的行为构成受贿罪，贪污罪，内幕交易、泄露内幕信息罪，决定执行有期徒刑16年，并处罚金人民币6250万元；对白向群受贿所得财物和内幕交易、泄露内幕信息违法所得及其孳息予以追缴，上缴国库，不足部分，继续追缴；贪污所得财物依法返还被害单位。白向群当庭表示服从判决，不上诉。 法院审理查明：1999年至2018年，被告人白向群利用担任共青团内蒙古自治区委书记，中共乌海市委副书记、乌海市人民政府市长，中共乌海市委书记，中共锡林郭勒盟委书记，内蒙古自治区人民政府副主席等职务上的便利，为有关单位和个人在配置煤炭资源、开发地产项目、承揽建设工程、职务调整晋升等事项上提供帮助，直接或者通过他人索取、收受上述单位和个人给予的财物，共计折合人民币8515万余元，其中索贿财物共计折合人民币1065万余元。 2008年至2012年，被告人白向群利用担任中共乌海市委书记、锡林郭勒盟委书记等职务上的便利，先后5次非法占有公共财物，共计折合人民币712万余元。 2010年10月初、2011年8月及2015年2月，被告人白向群从相关股票内幕信息知情人员处非法获取内幕信息，在内幕信息敏感期内，白向群筹措资金并指使他人用多个亲友账户买入上述股票，或者明示、暗示他人买入该股票，累计成交金额共计人民币4256万余元，非法获利共计人民币1717万余元；泄露上述内幕信息给他人，导致他人在内幕信息敏感期内买入上述股票，累计成交金额共计人民币4308万余元，非法获利共计人民币4052万余元。 57岁的白向群是十八大以来内蒙古的“第五虎”，十九大后内蒙古“第一虎”。白向群是辽宁人，但长期在内蒙古任职，2000年9月任内蒙古自治区团委书记、党组书记，后担任乌海、锡林郭勒盟等地主官，2012年5月任内蒙古自治区人民政府副主席、党组成员，直至2018年4月25日落马。 半年之后，中央纪委国家监委网站发布的“双开”通报中，语气相当严厉：白向群身为党的高级领导干部，丧失理想信念，毫无党性原则，私欲极度膨胀，把党和人民赋予的权力变为谋取私利的工具，大搞权钱交易，甘于被“围猎”，与不法商人勾肩搭背、沆瀣一气，贪得无厌、腐化堕落，严重违反党的纪律，构成职务违法并涉嫌犯罪，是党的十八大后不收敛、不收手的典型。 通报中提到，白向群“长期卖官鬻爵，严重破坏当地政治生态”。法院判决中提到，白向群多次索贿，数额特别巨大，多次为多人谋取职务提拔、调整，具有法定从重处罚情节。“卖官鬻爵”这个词，首次被用于苏荣，十九大之后被指卖官鬻爵的并不多，仅见于辽宁省副省长刘强和河北省人大常委副主任张杰辉的通报。这些人都曾担任一方主官，用人之风不正，落马后导致当地官场震荡，破坏当地政治生态。值得注意的是，白向群多次索贿，是主动向别人伸手索取财物，这样的行为性质更加恶劣。 白向群的庭审消息中提到，他到案后能够如实供述罪行，主动交代办案机关尚未掌握的大部分受贿、部分贪污犯罪事实，且检举揭发他人重大犯罪，具有重大立功表现，还积极退赃，法院对其从轻处罚。“检举揭发他人重大犯罪”属于重大立功，而重大犯罪是指犯罪嫌疑人、被告人可能被判处无期徒刑以上刑罚，或者案件在本省、自治区、直辖市或全国范围内有较大影响等情形。有重大立功表现者，可以减轻或者免除处罚，这已体现在白向群的刑期上。 值得一提的是，在白向群落马之后，内蒙古又有两名省部级干部被查，分别是内蒙古自治区人大常委会原党组副书记、副主任邢云，以及内蒙古自治区党委常委、呼和浩特市委书记云光中。加上十八大后内蒙古先后落马的四名中管干部，内蒙古的“老虎”已达七只。 两个“电老虎”退休仍被处理 10月24日8时，中央纪委国家监委网站发布消息：中国华电集团有限公司原党组副书记、总经理云公民涉嫌严重违纪违法，目前正接受中央纪委国家监委纪律审查和监察调查。 云公民是3天内中央纪委国家监委公布的第二个“电老虎”，就在30多个小时之前，10月22日17时，中央纪委国家监委网站发布消息：中国南方电网有限责任公司原党组书记、董事长李庆奎受到留党察看二年处分。耐人寻味的是，两人均在退休后被查，还曾是多年的老搭档。 公开资料显示，云公民是蒙古族，1950年9月生，由一名插队知青而成长为省部级干部。他曾长期在党政机构任职，1997年任内蒙古自治区副主席，2001年调任山西，担任过山西省委常委、太原市委书记等职。2006年，他进入神华集团任公司副董事长、党组副书记，2008年6月任华电集团党组副书记、总经理，2013年11月卸任。退休6年后被查，他晚年的宁静将被打破。 比云公民小6岁的李庆奎则是一名电力系统的资深干部。李庆奎是山东定陶人，曾任驻电力部（国家电力公司）监察局副局长、副局级纪检员，国家电力公司纪检组副组长、监察局长。2008年6月至2013年11月，他担任中国华电集团公司党组书记、副总经理，与云公民搭档了5年多。2013年11月，李庆奎任中国华电集团公司董事长、党组书记。2016年6月，他转任中国南方电网有限责任公司党组书记、董事长，直至2018年8月卸任。 退休14个月后，李庆奎被通报“断崖式”降级，而且通报中仍称其为“同志”。不同于大部分被处分中管干部先发布被查消息，后公开调查结果的惯例，李庆奎的处分通报令人颇感突然，此前并无他接受审查调查的消息传出。 通报中指出，李庆奎同志身为党的高级领导干部，长期担任中央管理企业主要领导职务，政治意识和纪律规矩意识淡漠，长期对家属失管失教，特权思想严重，违反中央八项规定精神，多次违规出入私人会所，多占公车且长期公车私用，超标准使用办公用房；违规提拔调整干部；以权谋私，本人及家属收受他人财物。 李庆奎同志的行为已违反党的纪律并构成职务违法，应予严肃处理。同时，鉴于李庆奎同志能够如实交代违纪违法问题且部分问题组织之前不掌握，主动全额上交违纪违法所得，认错悔错态度较好，可予从轻、减轻处理。依据《中国共产党纪律处分条例》等有关规定，经中央纪委常委会会议研究并报中共中央批准，决定给予李庆奎同志留党察看二年处分，按中国南方电网有限责任公司总部部门副职确定其退休待遇；收缴其违纪违法所得。 值得注意的是，华电集团、南方电网均被中央巡视组巡视过，且存在选人用人不当等共性问题。2019年3月至6月，中央第十一巡视组对南方电网党组进行了常规巡视，组长刘维佳在反馈时指出，南方电网党组党建工作责任落而不实，组织建设存在薄弱环节，选人用人问题反映较多；工程项目和设备采购等重点领域存在廉洁风险，基层腐败问题比较突出；对上轮中央巡视反馈问题整改落实打折扣，整改主体责任落实不到位。 2018年2月23日至5月23日，中央第十巡视组对华电集团党组进行了巡视。第十巡视组组长喻红秋指出，华电集团党组选人用人问题反映比较集中，坚持原则不够、遵守规矩不严等方面问题较为突出；有的领导人员不担当不作为，享乐主义、奢靡之风不同程度存在；腐败问题易发多发，工程建设、项目投资、企业并购等廉洁风险较大，“靠企吃企”、违规招标采购等问题仍比较突出。 同时，两个巡视组都收到反映一些领导人员的问题线索，已按规定转中央纪委、中央组织部等有关方面处理。 栏目主编：陈琼珂；",
          'correlation': 0,
          'count': 0,
          'createdTime': null,
          'domainType': '',
          'fans': 0,
          'gatherTime': '2019-12-13 17:36:05',
          'id': 0,
          'imagePath': '',
          'industry': '',
          'isWaste': false,
          'issueTime': '2019-12-13 17:36:50',
          'issueYmd': 20191213,
          'issueYmdh': 2019121317,
          'keyword': '',
          'manualCritique': '',
          'manualEventWords': '',
          'manualInstitution': '',
          'manualRegion': '',
          'manualScoreLevel': 0,
          'manualSummary': '',
          'manualTitle': '',
          'nickName': '',
          'operationData': false,
          'readed': 0,
          'rowkey': 'bceaf729926f2387_20191213000000_a4ee69c',
          'showTime': '2019-12-13 17:36:50',
          'showWords': [],
          'side': -1,
          'simId': '6ffd80646b52ebb2ead401dd2ced2ea9',
          'simNum': 153,
          'siteCls': '1',
          'siteName': '百度新闻',
          'subName': '百度新闻-中央巡视组',
          'title': '一周反腐看点：三天连打两个“电老虎”，他们的单位都进驻过中央巡视组',
          'url': 'http://cache.baidu.com/c?m=9d78d513d9d437ab4f9b96697b15c011694381132ba1d3020fd48439e0732d40506793ac51270773d8d13b275fa0131aacb22173441e3de7c893d0118ee1c175388850642347d00605d36efe9619388037912eb2f90ee6ccf33695a4d4d8d85551c056077e84f08e510313dd6ff45165a3b1983e541d4becba7072ff5d2374df3441c005a8&p=c66ae716d9c11cff57ec9f311747&newp=8b2a970e8edb33ff57ec9f3a5a5c92695d0fc20e38d0d501298ffe0cc4241a1a1a3aecbf22261a01d2c5796604a84f5ce8f03d723d0034f1f689df08d2ecce7e64d03f46&user=baidu&fm=sc&query=%D6%D0%D1%EB%D1%B2%CA%D3%D7%E9&qid=8535a34400000209&p1=7',
          'useId': 0,
          'verify': false,
          'warned': false,
          'waste': false,
          'word': '',
          'words1': '',
          'words2': '',
          'words3': ''
        }],
        'searchCount': true,
        'size': 30,
        'total': 41697
      }
      let records = data.records
      records.forEach((val, index, arr) => {
        if (val.title.length > 40) {
          arr[index].title = arr[index].title.substring(0, 40) + '...'
        }
      })
      commit('setIntellectSearchList', records)
      let currentPage = data.pages
      let pageSize = data.size
      let total = data.total
      commit('setPagination', { current_page: currentPage, page_size: pageSize, total: total })
    })
  }
}

export default {
  namespaced: true,
  state,
  actions,
  mutations
}
